Canvas map layer components
guardian/interactive-component-library pull request #229
Opened 2024-08-08 14:46 UTC by egargan

## What does this change?

This PR adds a React/JSX wrapper around the canvas map's layer components (`VectorLayer` and `TextLayer`).

Essentially, this means that we can replace this...

```jsx
 <Map {...args}>
    {{
      controls: [],
      layers: [outlineLayer, constituenciesLayer],
    }}
  </Map>
```

with this...

```jsx
<Map {...args}>
  <VectorLayer.Component
    features={new GeoJSON().readFeaturesFromObject(outline)}
    style={fillStyle}
  />
  <VectorLayer.Component
    features={new GeoJSON().readFeaturesFromObject(constituencies)}
    style={(feature) => {  /* ... */ }}
  />
</Map>
```

Much more React-y!

## `jsconfig.json` change

This change addresses the warnings that appear by our import statements.

<img width="600" alt="image" src="https://github.com/user-attachments/assets/47649c99-e0e8-406e-ad8f-a772bae3959a">

We're doing exactly what it says here, except we're using `Bundler` instead of `nodenext`. 

[As TS' docs explain](https://www.typescriptlang.org/tsconfig/#moduleResolution), we need this option so we can omit file extensions in our import paths. It's otherwise identical to `nodenext`.

## JSDoc types

This PR adds the first few JSDoc types to our exported components, meaning we get lovely helpful type info when using these components! 🥳 

(For the moment these types won't make it to consumers - it seems JSDoc comments are wiped in the minify step, something I'm looking into!)

<img width="400" alt="image" src="https://github.com/user-attachments/assets/e745671f-7719-43de-94f1-af7850ba5306">

<img width="600" alt="image" src="https://github.com/user-attachments/assets/20a01a97-bd0d-4a0d-8203-c9fa6428a46d">

2024-08-08 14:49 UTC, egargan commented on src/lib/components/molecules/canvas-map/lib/styles/Style.js
> + * TODO: is this meant to be a subset of the style attr?
@njdehoog am I right in thinking this class is meant to be a small subset of React's `CSSProperties` class? can we treat it as such? I gathered as much from how we get and set these styles in the map + layer code?

2024-08-08 14:49 UTC, egargan commented on src/lib/components/molecules/canvas-map/Map.jsx
> + * Map component that renders into a canvas.
Not very helpful documentation here, sorry! I was thinking we could do a wave of proper documentation for the most important components a bit later on?

2024-08-09 11:09 UTC, njdehoog requested changes
Looks good! Just a couple of comments.

2024-08-09 11:09 UTC, njdehoog commented on src/lib/components/molecules/canvas-map/lib/layers/VectorLayer.js
> +      map.addLayer(controller)
I think there is an edge case here that needs to be taken into account. If for whatever reason you want to hide the background layer and then unhide it later, it should still be rendered as the first layer.

Perhaps we can solve this in `MapContext.js` by doing something like this?
```js
useEffect(() => {
  const layers = toChildArray(children)
  const shouldUpdateMapLayers = arrayEquals(map.layers, children)
  // ...update map layers
}, [children])
```

2024-08-09 11:41 UTC, egargan commented on src/lib/components/molecules/canvas-map/lib/styles/Style.js
> + * TODO: is this meant to be a subset of the style attr?
Got it, thanks!

2024-08-12 11:00 UTC, egargan commented
Some extra discussion can be found on this detached commit: https://github.com/guardian/interactive-component-library/commit/e01eb8382347b9a71f0249efdb592853506d044c

2024-08-12 13:53 UTC, njdehoog approved these changes

2024-08-12 14:02 UTC, merged