Export types, remove CJS exports, don't bundle files
guardian/interactive-component-library pull request #246
Opened 2024-08-23 08:41 UTC by egargan

This PR makes a number of changes to our build process, with the aim of improving the experience for library consumers.

## Maintaining source directory structure in dist

Rather than bundling every source file into a single `index.js` output, this PR changes our build config to keep the directory structure that we have in `src/lib`.

For our component library, considering it'll only ever be consumed by the interactives and perhaps neighbouring teams using our atom template, bundling isn' really necessary, and it comes at the cost of relying more on flaky sourcemaps.

This change was motivated by struggling with troubleshooting components in the US elections project: our stack traces aren't pointing to the correct places in source code. Where possible, not relying on source maps and having our library output resemble source files as closely as possible is a good thing.

(In my opinion, ideally, we'd only compile our SCSS modules code and leave the Preact components as-is, but I wasn't able to achieve this.)

## Export types

Using the [vite-plugin-dts](https://github.com/qmhc/vite-plugin-dts) plugin, we now generate `.d.ts` files that sit alongside their source file. This is needed in cases where we rely on `/** typedef {...} */` JSDoc ([e.g. here](https://github.com/guardian/interactive-component-library/blob/main/src/lib/components/molecules/canvas-map/Map.jsx#L9-L15)), which esbuild refuses to output, leaving us with dangling type names.

## Don't output CJS

This is less about developer experience but seems like an easy way to reduce complexity. These days, ESM is the dominant and preferred module system. CJS should only be supported by libraries with very generous backwards compatibility requirements, which we don't have!

2024-08-23 11:08 UTC, egargan commented
I'm having some trouble with this after all :/

I'm not sure exactly what the problem is, but when installing the component library, it's related to a transitive dependency not being resolved at build time.

![image](https://github.com/user-attachments/assets/ff4613bc-bdb3-4535-b448-010ab5b6e951)

2024-08-23 11:31 UTC, njdehoog requested changes
Thanks for tackling this. I agree that the type definitions should be accessible, and that debugging should be as easy as possible.

The Vite config can be simplified I think. Here's my suggestion: https://github.com/guardian/interactive-component-library/blob/misc-build-improvements-niels/vite.config.js

I haven't checked if this works with publishing to NPM, have you? That's an important one.

Happy to discuss making changes to dependencies vs peer dependencies.

2024-08-23 13:10 UTC, egargan commented
> The Vite config can be simplified I think. Here's my suggestion: https://github.com/guardian/interactive-component-library/blob/misc-build-improvements-niels/vite.config.js

Great shout, I'll push that up to this branch.

> I haven't checked if this works with publishing to NPM, have you? That's an important one.

Nope, will do, I'll try an rc release on this branch!

> Happy to discuss making changes to dependencies vs peer dependencies.

It's literally just this preact-transitioning dep that's causing us issues! Removing it solves the build error, in the US elections page at least.

2024-09-03 10:19 UTC, egargan commented
I opened PRs for preact-merge-refs and for preact-transitioning to fix this issue (https://github.com/fakundo/preact-merge-refs/pull/1, https://github.com/fakundo/preact-transitioning/pull/44).

Now that these have been merged, we're good to go! Importing the new bundle that this PR produces works perfectly.

This PR's now ready to be reviewed and merged 🥳

2024-09-03 10:24 UTC, egargan commented
> Happy to discuss making changes to dependencies vs peer dependencies.

I did a bit of digging into this, and our current set of dependencies and peer dependencies make sense.

[Having read this article](https://nodejs.org/en/blog/npm/peer-dependencies/), it sounds like peer dependencies are not suitable for dependencies like preact-transitioning. Peer dependencies essentially tell consuming projects that...

_> This package is designed to work with (e.g.) Preact version 2.1.0, and only version 2.1.0. When you install me, don’t just install my Preact 2.1.0 as a dependency and continue using whatever version you’re using — you have to use Preact 2.1.0._

These rules don't apply to preact-transitioning. We use it to give our Modal component a fancy transition. It doesn't matter if e.g. the US elections tracker uses, doesn't use, or uses a different version of preact-transitioning.

2024-09-03 13:51 UTC, ajwl approved these changes
building into a nice clean dist folder ✅ 
nb: have not deployed to npm but ^ see you have above 👍 

thanks for doing this, looks very useful

2024-09-03 13:57 UTC, merged